### ISSUE TITLE
Docs site: Sidebars

### ISSUE THREAD

**Issue by gokul472** [overture-stack/roadmap#49]
This ticket is for the sidebar menu links

**Left sidebar:**: how multiple levels will be shown for the sidebars.
- [ ] They can be expanded and collapsed 
- [ ] Default, hover, active states
- [ ] Link to the Github repo for that product.
- [ ] Should be fixed - so menu should follow the user as they scroll down the page (eg. https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/import_data).

Zeplin: https://zpl.io/2v4YjYn
For more styles for tertiary sections: https://zpl.io/VQwYJKn

<img width="742" alt="2020-07-31_1152" src="https://user-images.githubusercontent.com/18424138/89052999-8c0a7380-d324-11ea-9385-938ddf31cbf7.png">

**Right sidebar:**
- [ ] This is the table of contents for the page (based on content headers on page): all subsections are show by default - no expand and collapse here
- [ ] As user scrolls down the page, this TOC menu follows them and highlights (active state) which section is in the current viewing pain (example: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/import_data)

zeplin: https://zpl.io/VQwYJKn
<img width="597" alt="Screen Shot 2020-07-31 at 12 11 45 PM" src="https://user-images.githubusercontent.com/18424138/89054612-1ce24e80-d327-11ea-806c-05ec31a4708b.png">

---

## Scope/testing additions

- made horizontal lines darker site-wide
- added a link component that detects if links are internal or external. internal links will now use Gatsby routing and external links will open in new tabs.
  - as an enhancement this should be implemented site-wide, i.e. every instance of `<a href>` should be using this link component.
- updated Markdown example, removed info that conflicts with the code formatting settings for this project.
- improved colour contrast of links in warning & note boxes.

**Comment by samrichca** [comment]
what happens when you scroll down?

I'm imagining...

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/97ee9964-6ab7-4c40-b007-03d6abcd0269)
![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/49c6787f-8e94-4ac2-9e7e-f40801ae01ef)

**Comment by b-f-chan** [comment]
Include mobile version in scope of ticket - Follow hamburger UX similar to ARGO docs, example:
https://docs.icgc-argo.org/docs/submission/submission-overview

**Comment by samrichca** [comment]
https://github.com/overture-stack/website/pull/94

**Comment by samrichca** [comment]
updates on file & URL structure. follows the ICGC ARGO docs structure.

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/e01e8934-4a56-47bb-b923-ef94e7d103c0)

![image.png](https://images.zenhubusercontent.com/5d2e194240c06427886a21ee/afdf0309-b914-4222-9e57-4956067f5117)

**Comment by kcullion** [comment]
@samrichca Some feedback as discussed on slack:

- [ ] Let's just show the h1 and h2 level headings in the right table of contents sidebar, or else this could get quite overwhelming.

(like github docs: https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo#step-1-set-up-git)
<img width="1480" alt="2020-12-02_09-52-03" src="https://user-images.githubusercontent.com/18424138/100890886-b876fd80-3486-11eb-8a99-f074f3cd8cab.png">


- [ ] Let's make it so the content starts at the same place on each page, with or without the right sidebar. So it isn't jumping around when navigating
![image (55)](https://user-images.githubusercontent.com/18424138/100892367-42739600-3488-11eb-9393-e134ffe3e3ae.png)

- [ ] Since the left menu can get pretty long, let's move the github button to the top right of the page template (as it's an important link to get to) https://zpl.io/VQwYJKn
On mobile, just keep it out of the right sidebar like:
![image](https://user-images.githubusercontent.com/18424138/100900567-f8db7900-3490-11eb-8014-4acd71c54040.png)

- [ ] There's a resolution just before the menus disappear for mobile where the blue menu button shows at the bottom, but does not open to anything: 
![image](https://user-images.githubusercontent.com/18424138/100902040-810e4e00-3492-11eb-9c1d-cce7c6fc6074.png)

- [ ] the left sidebar menu is doing that thing where on refresh, it's losing the active state:
![image](https://user-images.githubusercontent.com/18424138/100902363-d0ed1500-3492-11eb-9e2f-fd283c37012f.png)

**Comment by samrichca** [comment]
thanks for the feedback @kcullion !

- changed right sidebar to 2 levels
- made the spacing/position of the main column more consistent
- made nav highlighting work after refresh, same solution as the megamenu
- moved github button to top right
- fixed responsive issues, all mobile styling will kick in at 1160px

https://5fc7d3de404c1ab8f8af3b69--overture.netlify.app/documentation/song/markdown/

cc @b-f-chan

**Comment by kcullion** [comment]
looks great @samrichca thanks!

**Comment by rosibaj** [comment]
Side bar feedback (Dec 02)
- keep at least 50px from left side bar (the design is measuring 50px..but can eyeball what looks good in the browser)
- let the content expand based on screen size to the right bar

**Comment by rosibaj** [comment]
Tested https://5fc948e86578eb01151e907b--overture.netlify.app/documentation/song/markdown/  

@samrichca this looks amazing!  I think we are done with sidebars for now!
