### ISSUE TITLE
Docs Site: Links

### ISSUE THREAD

**Issue by samrichca** [overture-stack/roadmap#97]
problem:
- gatsby requires trailing slashes in URLs. leaving them out can break the routing or cause nav items to not highlight properly.
- gatsby has a built-in link component for internal routing and the documentation discourages using this for external links. there's no built-in method for differentiating between the two, which causes issues when you don't know in advance if the link will be internal or external (i.e. in markdown).

solution:
- use proper-url-join to ensure URL formatting with trailing slashes
  - make a utility that uses this library with the desired settings
  - update gatsby-node.js to use this utility when creating pages
- make a reusable link component that determines if the link is internal or external and selects the correct element (gatsby link vs html anchor tag) **(this is done already)**
  - for internal links, enforce trailing slashes using the above utility
  - external links should have target blank etc
- use this across the whole site for consistency

**Comment by samrichca** [comment]
testing notes:

- every link & button on the site changed
- this could cause visual defects as well as behavioural issues (links or buttons not doing what they're supposed to)

**Comment by samrichca** [comment]
https://5fe240e3ccb7e463e2a8f9bc--overture.netlify.app/

**Comment by b-f-chan** [comment]
Do not need to test all pages, just the major navigation areas (header, footer, pages)

**Comment by samrichca** [comment]
updated scope: all links were changed because I moved them to constants/variables, so they all need to be tested

https://5ffe0d7c48b4b20125f03026--overture.netlify.app/

**Comment by b-f-chan** [comment]
Tested all links and buttons, all work except 2 issues found:

(1) Slack invite link broken in the header and in middle of the Contact page.  The link on prod works and uses http (http://slack.overture.bio/, but the link in lab netlify uses https and is broken (https://slack.overture.bio/).  However, I'm not sure why the invite link is using unsecure http in the first place.

![BrokenSlackInviteLink.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/8adec79b-c3cb-4f74-a45c-bcf2e00aadd4)

(2) On the OncoJS Products page, the live example link for Pathway Viewer incorrectly links to GDC Portal, instead of an actual example on ICGC Portal.  This is actually a prod issue and is already broken there, but if you can fix it as part of this ticket would be great.  If not, I can create separate ticket.  Correct link should be: https://dcc.icgc.org/genesets/R-HSA-1236974/pathway-viewer

![IncorrectPathwayViewerLink.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/6e097a4c-32ac-4238-b976-a00e4249bfec)

**Comment by samrichca** [comment]
https://6001c19d0c48c351bd02d758--overture.netlify.app/products/oncojs/

**Comment by b-f-chan** [comment]
Re-tested at netlify above, slack invite link and pathway viewer live example link fixed and go to correct pages now.
